[[project]]
name = "Boon"
desc = "Programming language for writing apps"
tags = ["language", "functional", "persistent", "staticaly-typed"]
links = [
    { name = "github", url = "https://github.com/BoonLang/boon" },
    { name = "playground", url = "https://boon-playground.kavik.cz" },
]

[[project]]
name = "MoonZoon"
desc = "Rust fullstack framework"
tags = ["rust", "fullstack", "framework", "wasm", "messages"]
links = [
    { name = "github", url = "https://github.com/MoonZoon/MoonZoon" },
]

[[project]]
name = "FastWave"
desc = "Modern GTKWave alternative"
tags = ["waveform", "viewer", "wasm", "vcd", "fst", "fpga", "tauri"]
links = [
    { name = "github", url = "https://github.com/FastWaveViewer/FastWave" }
]

[[project]]
name = "Fast2D"
desc = "Draw shapes and text using Canvas Web API or wgpu"
tags = ["2D", "graphics", "canvas", "wgpu", "webgl", "webgpu", "wasm"]
links = [
    { name = "github", url = "https://github.com/FastWaveViewer/Fast2D" }
]

[[project]]
name = "Persons.pro"
desc = "The app for freelancers, open-source creators and digital product makers"
tags = ["hire", "sponsor", "sell"]
links = [
    { name = "website", url = "https://persons.pro/" },
]

[[project]]
name = "LocalSearch"
desc = "Client-side full-text library"
tags = ["search", "full-text", "autocomplete", "rust", "wasm"]
links = [
    { name = "github", url = "https://github.com/Stremio/local-search" },
]
